#version 430
// GENERATED by turing glsl_backend.emit_program_source -- do not edit by hand.
//
// Fused elementwise program: every intermediate value is a local (a register),
// so only feeds and the single output ever touch memory. This is the whole
// reason a FusedProgram is worth running on a GPU rather than operation
// by instruction.
layout(local_size_x = 256) in;

uint turing_linear_gid() {
    uvec3 launch_size = gl_NumWorkGroups * gl_WorkGroupSize;
    return gl_GlobalInvocationID.x
         + gl_GlobalInvocationID.y * launch_size.x
         + gl_GlobalInvocationID.z * launch_size.x * launch_size.y;
}

layout(std430, binding = 0) buffer Arena { uint arena[]; };

uniform uint u_count;
uniform uint u_extent[1];
uniform uint u_slot[4];

void main() {
    {
        uint gid = turing_linear_gid();
        if (gid < u_extent[0]) {
            float s0 = uintBitsToFloat(arena[u_slot[0] + (gid)]);
            float s1 = uintBitsToFloat(arena[u_slot[1] + (gid)]);
            float s2 = uintBitsToFloat(arena[u_slot[2] + (gid)]);
            float s3 = s0 * s2;
            float s4 = float(1.0) - s2;
            float s5 = s1 * s4;
            float s6 = s3 + s5;
            float s7 = s6 * float(255.0);
            arena[u_slot[3] + (gid)] = floatBitsToUint(s7);
        }
    }
}

