#version 430
// GENERATED by turing glsl_backend.emit_program_source -- do not edit by hand.
//
// Fused elementwise program: every intermediate value is a local (a register),
// so only feeds and the single output ever touch memory. This is the whole
// reason a FusedProgram is worth running on a GPU rather than operation
// by instruction.
layout(local_size_x = 256) in;

uint turing_linear_gid() {
    uvec3 launch_size = gl_NumWorkGroups * gl_WorkGroupSize;
    return gl_GlobalInvocationID.x
         + gl_GlobalInvocationID.y * launch_size.x
         + gl_GlobalInvocationID.z * launch_size.x * launch_size.y;
}

layout(std430, binding = 0) buffer Arena { uint arena[]; };

uniform uint u_count;
uniform uint u_extent[1];
uniform uint u_slot[5];

void main() {
    {
        uint gid = turing_linear_gid();
        if (gid < u_extent[0]) {
            float s0 = uintBitsToFloat(arena[u_slot[0] + (gid)]);
            float s1 = cos(s0);
            float s2 = float(0.5) * s1;
            float s3 = float(0.5) + s2;
            float s4 = s0 - float(2.094395102393195);
            float s5 = cos(s4);
            float s6 = float(0.5) * s5;
            float s7 = float(0.5) + s6;
            float s8 = s0 - float(4.18879020478639);
            float s9 = cos(s8);
            float s10 = float(0.5) * s9;
            float s11 = float(0.5) + s10;
            arena[u_slot[1] + (gid)] = floatBitsToUint(s0);
            arena[u_slot[2] + (gid)] = floatBitsToUint(s3);
            arena[u_slot[3] + (gid)] = floatBitsToUint(s7);
            arena[u_slot[4] + (gid)] = floatBitsToUint(s11);
        }
    }
}

