"""A chassis editor: draw linkages in 3D and say what every edge is.

The point of this is to stop objects being things somebody wrote a
builder function for. An object here is a list of nodes and a list of
segments, each segment naming a type from the production game's own
vocabulary (segment_types.py), and the file it saves is a graph the
production physics can run. The turret, the scissor lift and anything
else become documents rather than code.

    python chassis_editor.py [object.json]

WHAT THE MOUSE DOES

    left click on empty space   place a node at the work plane
    left click on a node       select it; select a second one and a
                               segment of the current type is made
                               between them
    right click on a node      delete it, and every segment on it
    drag with the middle       orbit the camera
    wheel                      zoom

WHAT THE KEYS DO

    TAB / shift-TAB     next / previous family of segment type
    [ ]                 previous / next type within the family
    , .                 previous / next NODE type for new nodes
    PgUp / PgDn         raise / lower the work plane
    G                   snap to grid on or off
    V                   validate the structure
    E                   export the production graph
    S / L               save / load the editor document
    DEL                 clear the current selection
    X                   delete the last segment made

WHY A WORK PLANE

A mouse gives two numbers and a position in space needs three, so
every click resolves against a horizontal plane at a chosen height.
Raise the plane, click, lower it, click again: that is how a
three-dimensional frame gets drawn with a two-dimensional pointer, and
it is what every CAD package does for the same reason.
"""
from __future__ import annotations

import json
import math
import sys
from dataclasses import dataclass, field, asdict
from pathlib import Path

import numpy as np
import pygame

sys.path.insert(0, str(Path(__file__).resolve().parent))

import segment_types as st
from gl_text import TextLayer
from engine_gl_view import EngineGLView

WINDOW_SIZE = (1500, 880)
VIEW_SIZE = 860
PANEL_X = VIEW_SIZE + 24
BG = (18, 18, 22)
TEXT = (210, 215, 225)
DIM = (130, 135, 145)
HOT = (255, 175, 70)
OK = (120, 220, 140)
BAD = (255, 110, 110)
PICK_RADIUS_PX = 14.0


# =====================================================================
#  THE DOCUMENT
# =====================================================================
@dataclass
class EditorNode:
    identity: str
    kind: str
    position: list
    mass_kg: float = 20.0
    fixed: bool = False


@dataclass
class EditorSegment:
    identity: str
    a: str
    b: str
    type_key: str
    parameters: dict = field(default_factory=dict)


@dataclass
class EditorDocument:
    """What the editor is editing. Deliberately plain: a list of nodes
    and a list of segments, so it can be written by hand, generated by
    a script, or drawn with the mouse, and all three produce the same
    thing."""
    identity: str = "untitled-object"
    nodes: list = field(default_factory=list)
    segments: list = field(default_factory=list)
    _counter: int = 0

    def new_name(self, prefix: str) -> str:
        self._counter += 1
        return f"{prefix}.{self._counter:03d}"

    def node_by_id(self, identity: str):
        return next((n for n in self.nodes if n.identity == identity), None)

    def add_node(self, position, kind: str) -> EditorNode:
        spec = st.NODE_BY_KEY.get(kind)
        n = EditorNode(identity=self.new_name("node"), kind=kind,
                       position=[float(v) for v in position],
                       mass_kg=spec.default_mass_kg if spec else 20.0,
                       fixed=bool(spec.fixed) if spec else False)
        self.nodes.append(n)
        return n

    def add_segment(self, a: str, b: str, type_key: str) -> EditorSegment | None:
        if a == b:
            return None
        if any(s for s in self.segments
               if {s.a, s.b} == {a, b} and s.type_key == type_key):
            return None            # that member already exists
        spec = st.get(type_key)
        s = EditorSegment(identity=self.new_name("seg"), a=a, b=b,
                          type_key=type_key, parameters=dict(spec.defaults()))
        self.segments.append(s)
        return s

    def delete_node(self, identity: str) -> None:
        self.nodes = [n for n in self.nodes if n.identity != identity]
        self.segments = [s for s in self.segments
                         if s.a != identity and s.b != identity]

    # ---------------- the two things it produces ----------------
    def to_json(self) -> str:
        return json.dumps({"identity": self.identity,
                           "nodes": [asdict(n) for n in self.nodes],
                           "segments": [asdict(s) for s in self.segments]}, indent=1)

    @classmethod
    def from_json(cls, text: str) -> "EditorDocument":
        raw = json.loads(text)
        doc = cls(identity=raw.get("identity", "untitled-object"))
        doc.nodes = [EditorNode(**n) for n in raw.get("nodes", [])]
        doc.segments = [EditorSegment(**s) for s in raw.get("segments", [])]
        doc._counter = len(doc.nodes) + len(doc.segments)
        return doc

    def to_production_graph(self) -> dict:
        """The whole reason the editor exists: a document the production
        physics can run, with every member carrying its rest length,
        section, damage law and bushing."""
        from turret_production import ProductionGraph
        g = ProductionGraph(identity=f"{self.identity}/production")
        for n in self.nodes:
            attrs = {"mass_kg": float(n.mass_kg), "mass_in_total": True, "in_view": True}
            if n.fixed:
                attrs["fixed_to"] = "world"
            g.node(n.identity, n.position, n.kind, **attrs)
        for s in self.segments:
            spec = st.get(s.type_key)
            g.edge(s.identity, s.a, s.b, spec.key,
                   radius=float(s.parameters.get("radius_m", spec.default_radius_m)),
                   palette=spec.palette_role,
                   frame_mount=bool(spec.family in ("joint", "breakable")),
                   **{k: v for k, v in s.parameters.items() if k != "radius_m"})
        return g

    def to_view_graph(self) -> dict:
        """A cheap document for the viewport: same shape, no physics."""
        nodes = [{"identity": n.identity, "kind": n.kind,
                  "reference_position": list(n.position),
                  "body_half_extent_m": [0.045, 0.045, 0.045],
                  "mass_kg": n.mass_kg, "material": "steel-plate", "in_view": True}
                 for n in self.nodes]
        edges = []
        for s in self.segments:
            spec = st.get(s.type_key)
            edges.append({"identity": s.identity, "a": s.a, "b": s.b,
                          "constraint": spec.key, "radius": spec.default_radius_m,
                          "material": _view_material(spec), "in_view": True})
        return {"schema": "engine-toy-drivetrain-graph-v1", "identity": self.identity,
                "machine": True, "nodes": nodes, "edges": edges}


def _view_material(spec: st.SegmentType) -> str:
    return {"structural": "steel-plate", "joint": "hardened-steel", "spring": "pressed-steel",
            "actuator": "hardened-steel", "drive": "steel-shaft", "routed": "steel-pipe",
            "breakable": "cast-iron", "impulse": "gun-steel"}.get(spec.family, "steel-plate")


# =====================================================================
#  PICKING
# =====================================================================
def _project(point, view) -> tuple | None:
    """Where a world point lands on screen, using the view's own camera
    so the editor and the render can never disagree about it."""
    mvp = getattr(view, "_last_mvp", None)
    if mvp is None:
        return None
    p = np.asarray(list(point) + [1.0], dtype=np.float64)
    clip = np.asarray(mvp, dtype=np.float64).T @ p if np.asarray(mvp).shape == (4, 4) else None
    if clip is None or abs(clip[3]) < 1e-9:
        return None
    ndc = clip[:3] / clip[3]
    if not (-1.2 < ndc[0] < 1.2 and -1.2 < ndc[1] < 1.2):
        return None
    x = (ndc[0] * 0.5 + 0.5) * VIEW_SIZE
    y = (1.0 - (ndc[1] * 0.5 + 0.5)) * VIEW_SIZE
    return float(x), float(y), float(ndc[2])


def _ray_plane(ray, height: float):
    """Where a pick ray crosses the work plane."""
    o = np.asarray(ray.origin, dtype=np.float64)
    d = np.asarray(ray.direction, dtype=np.float64)
    if abs(d[1]) < 1e-9:
        return None
    t = (height - o[1]) / d[1]
    if t <= 0.0:
        return None
    return o + d * t


def _nearest_node(doc: EditorDocument, ray, max_distance_m: float = 0.12):
    """The node closest to the pick ray, if any is close enough.

    Done in world space against the ray rather than in screen space
    against projected points: it needs no camera matrix and it behaves
    the same however the view is oriented."""
    o = np.asarray(ray.origin, dtype=np.float64)
    d = np.asarray(ray.direction, dtype=np.float64)
    d = d / max(np.linalg.norm(d), 1e-12)
    best, best_dist = None, max_distance_m
    for n in doc.nodes:
        p = np.asarray(n.position, dtype=np.float64)
        along = float(np.dot(p - o, d))
        if along <= 0.0:
            continue
        dist = float(np.linalg.norm(p - (o + d * along)))
        if dist < best_dist:
            best, best_dist = n, dist
    return best


# =====================================================================
#  THE APPLICATION
# =====================================================================
def main(argv: list[str]) -> None:
    pygame.init()
    pygame.display.set_mode(WINDOW_SIZE, pygame.OPENGL | pygame.DOUBLEBUF)
    pygame.display.set_caption("chassis editor")
    font = pygame.font.SysFont("consolas", 15)
    text = TextLayer(font, *WINDOW_SIZE)
    view = EngineGLView(width=VIEW_SIZE, height=VIEW_SIZE, covers_off=False,
                        animation_divisions=[0.0], detail=0.5)

    doc = EditorDocument()
    path = Path(argv[1]) if len(argv) > 1 else Path("object.json")
    if path.is_file():
        doc = EditorDocument.from_json(path.read_text(encoding="utf-8"))

    family_index = 0
    type_index = 0
    node_type_index = 0
    work_height = 0.0
    snap = True
    selected: list = []
    messages: list = []
    dirty = True

    def current_family() -> str:
        return st.FAMILIES[family_index % len(st.FAMILIES)]

    def current_type() -> st.SegmentType:
        pool = st.of_family(current_family())
        return pool[type_index % len(pool)] if pool else st.SEGMENT_TYPES[0]

    def current_node_type() -> st.NodeType:
        return st.NODE_TYPES[node_type_index % len(st.NODE_TYPES)]

    def say(line: str) -> None:
        messages.append(line)
        del messages[:-8]

    def refresh() -> None:
        nonlocal dirty
        view.set_graph(doc.to_view_graph())
        while view.bake_next():
            pass
        dirty = False

    refresh()
    say(f"{len(doc.nodes)} nodes, {len(doc.segments)} segments")

    clock = pygame.time.Clock()
    running = True
    orbiting = False
    while running:
        dt = clock.tick(60) / 1000.0
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            elif event.type == pygame.MOUSEBUTTONDOWN:
                mx, my = event.pos
                inside = mx < VIEW_SIZE and my < VIEW_SIZE
                if event.button == 2 and inside:
                    orbiting = True
                elif event.button == 4:
                    view._zoom = max(0.25, view._zoom * 0.9)
                elif event.button == 5:
                    view._zoom = min(6.0, view._zoom * 1.1)
                elif event.button in (1, 3) and inside:
                    ray = view.pick_ray(mx, my)
                    if ray is None:
                        say("view is not ready yet")
                        continue
                    hit = _nearest_node(doc, ray)
                    if event.button == 3:
                        if hit is not None:
                            doc.delete_node(hit.identity)
                            selected.clear()
                            say(f"deleted {hit.identity}")
                            dirty = True
                        continue
                    if hit is not None:
                        selected.append(hit.identity)
                        if len(selected) == 2:
                            spec = current_type()
                            seg = doc.add_segment(selected[0], selected[1], spec.key)
                            say(f"{spec.label}: {selected[0]} -> {selected[1]}"
                                if seg else "that member already exists")
                            selected.clear()
                            dirty = True
                        else:
                            say(f"selected {hit.identity}")
                    else:
                        point = _ray_plane(ray, work_height)
                        if point is None:
                            say("click misses the work plane -- orbit the camera")
                            continue
                        if snap:
                            point = np.round(np.asarray(point) / 0.05) * 0.05
                        n = doc.add_node(point, current_node_type().key)
                        say(f"{current_node_type().label} at "
                            f"({n.position[0]:.2f}, {n.position[1]:.2f}, {n.position[2]:.2f})")
                        dirty = True
            elif event.type == pygame.MOUSEBUTTONUP and event.button == 2:
                orbiting = False
            elif event.type == pygame.MOUSEMOTION and orbiting:
                view._angle_rad += event.rel[0] * 0.01
                view._elevation = max(-2.5, min(2.5, view._elevation - event.rel[1] * 0.01))
            elif event.type == pygame.KEYDOWN:
                shift = pygame.key.get_mods() & pygame.KMOD_SHIFT
                if event.key == pygame.K_ESCAPE:
                    running = False
                elif event.key == pygame.K_TAB:
                    family_index += -1 if shift else 1
                    type_index = 0
                    say(f"family: {current_family()}")
                elif event.key == pygame.K_LEFTBRACKET:
                    type_index -= 1
                elif event.key == pygame.K_RIGHTBRACKET:
                    type_index += 1
                elif event.key == pygame.K_COMMA:
                    node_type_index -= 1
                elif event.key == pygame.K_PERIOD:
                    node_type_index += 1
                elif event.key == pygame.K_PAGEUP:
                    work_height += 0.10
                    say(f"work plane y = {work_height:.2f} m")
                elif event.key == pygame.K_PAGEDOWN:
                    work_height -= 0.10
                    say(f"work plane y = {work_height:.2f} m")
                elif event.key == pygame.K_g:
                    snap = not snap
                    say(f"grid snap {'on' if snap else 'off'}")
                elif event.key == pygame.K_DELETE:
                    selected.clear()
                    say("selection cleared")
                elif event.key == pygame.K_x and doc.segments:
                    gone = doc.segments.pop()
                    say(f"removed {gone.identity}")
                    dirty = True
                elif event.key == pygame.K_v:
                    try:
                        problems = doc.to_production_graph().check()
                    except Exception as exc:
                        problems = [f"cannot build: {exc}"]
                    say("structure PASSES" if not problems
                        else f"{len(problems)} problem(s): {problems[0]}")
                    for p in problems[1:4]:
                        say(f"   {p}")
                elif event.key == pygame.K_e:
                    out = path.with_suffix(".production.json")
                    g = doc.to_production_graph()
                    out.write_text(json.dumps(g.as_document(), indent=1), encoding="utf-8")
                    say(f"exported {len(g.nodes)} nodes / {len(g.edges)} members -> {out.name}")
                elif event.key == pygame.K_s:
                    path.write_text(doc.to_json(), encoding="utf-8")
                    say(f"saved {path.name}")
                elif event.key == pygame.K_l and path.is_file():
                    doc = EditorDocument.from_json(path.read_text(encoding="utf-8"))
                    selected.clear()
                    say(f"loaded {path.name}")
                    dirty = True

        if dirty:
            refresh()

        text.begin_frame()
        tex = view.render_gpu(crank_angle_deg=0.0, spin=False, dt=dt, throttle_frac=0.0)
        text.compositor.draw_texture(tex, 0, 0, VIEW_SIZE, VIEW_SIZE, *WINDOW_SIZE, flip_v=True)

        y = 14
        spec = current_type()
        text.draw(f"{doc.identity}    {len(doc.nodes)} nodes   {len(doc.segments)} segments",
                  PANEL_X, y, TEXT); y += 26
        text.draw(f"family   {current_family()}   (TAB)", PANEL_X, y, DIM); y += 20
        text.draw(f"segment  {spec.label}", PANEL_X, y, HOT); y += 20
        text.draw(f"         {spec.key}", PANEL_X, y, DIM); y += 20
        if spec.origin != "production":
            text.draw("         (ours -- added to the palette)", PANEL_X, y, OK); y += 20
        if spec.note:
            for chunk in _wrap(spec.note, 58):
                text.draw(f"   {chunk}", PANEL_X, y, DIM); y += 18
        y += 6
        for name, value in spec.parameters:
            text.draw(f"   {name:30s} {value}", PANEL_X, y, DIM); y += 17
        y += 10
        text.draw(f"node     {current_node_type().label}   (, .)", PANEL_X, y, TEXT); y += 22
        text.draw(f"plane    y = {work_height:+.2f} m   (PgUp/PgDn)", PANEL_X, y, TEXT); y += 20
        text.draw(f"snap     {'0.05 m' if snap else 'off'}   (G)", PANEL_X, y, TEXT); y += 26
        if selected:
            text.draw(f"selected {selected[0]} -- pick its partner", PANEL_X, y, HOT); y += 22
        y += 8
        for line in messages[-8:]:
            colour = BAD if "problem" in line or "cannot" in line else (
                OK if "PASSES" in line or "exported" in line else DIM)
            text.draw(line, PANEL_X, y, colour); y += 18
        text.draw("V validate   E export   S save   L load   X undo segment",
                  PANEL_X, WINDOW_SIZE[1] - 28, DIM)
        text.end_frame()
        pygame.display.flip()

    text.close()
    pygame.quit()


def _wrap(s: str, width: int) -> list[str]:
    words, line, out = s.split(), "", []
    for w in words:
        if len(line) + len(w) + 1 > width:
            out.append(line); line = w
        else:
            line = f"{line} {w}".strip()
    if line:
        out.append(line)
    return out


if __name__ == "__main__":
    main(sys.argv)
